version: '3.7'
services:

  appquarium-php-apigateway:
    image: deozza/appquarium-apigateway
    build:
      context: .
      dockerfile: .docker/php/Dockerfile.dev
    container_name: appquarium-php-apigateway
    volumes:
      - ./apiGateway/:/var/www/apiGateway
    restart: on-failure
    ports:
      - 8000:8000