version: '3.7'
services:

  appquarium-php-apigateway:
    image: deozza/appquarium-apigateway
    build:
      context: .
      dockerfile: .docker/php/Dockerfile.prod
      target: prod
    container_name: appquarium-php-apigateway
    restart: on-failure
    user: '1000:1000'
