FROM php:7.3-fpm as base

RUN apt-get update \
    && apt-get install -y libzip-dev zip libcurl4-openssl-dev pkg-config libssl-dev gnupg

RUN set -xe \
    && docker-php-ext-install zip

RUN pecl install apcu \
    && docker-php-ext-enable apcu

COPY .docker/php/ini/conf.d/memory_limit.ini /usr/local/etc/php/conf.d
COPY apiGateway/ /var/www/apiGateway

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls \
    && mv composer.phar /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1
RUN mkdir -p /var/www/.composer && chown -R www-data /var/www/.composer

RUN PATH=$PATH:/var/www/apiGateway/vendor/bin:bin

WORKDIR /var/www/apiGateway

EXPOSE 9000

CMD ["php-fpm"]