name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker containers
      run: docker-compose up -d
    - name: Launch tests
      run: docker-compose exec -T -u root appquarium-php-apigateway bin/phpunit
    - name: Login to Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Tag image
      run: docker tag deozza/appquarium-apigateway deozza/appquarium-apigateway:${{ steps.vars.outputs.sha_short }}
    - name: Push to Docker tagged image
      run: docker push deozza/appquarium-apigateway:${{ steps.vars.outputs.sha_short }}
    - name: latest image
      run: docker tag deozza/appquarium-apigateway deozza/appquarium-apigateway:latest
    - name: Push to Docker
      run: docker push deozza/appquarium-apigateway:latest