name: Integration tests

on:
  push:
    branches:
      - hotfix
      - develop
      - feature
    paths:
      - 'apiGateway/config/**'
      - 'apiGateway/src/**'
      - 'apiGateway/tests/**'
      - '.docker/**'
      - '.github/workflows/integration_testing.yml'
      - 'docker-compose.dev.yml'
      - 'docker-compose.test.yml'
      - 'apiSpecies/composer.json'
      - 'apiSpecies/composer.lock'
      - 'apiSpecies/symfony.lock'

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker test containers
      run: docker-compose -f docker-compose.test.yml up -d
    - name: Check composer
      run: docker-compose -f docker-compose.test.yml exec -T -u root appquarium-php-apigateway composer validate
    - name: Install composer dependencies
      run: docker-compose -f docker-compose.test.yml exec -T -u root appquarium-php-apigateway composer install --prefer-dist --no-scripts --no-progress -q -o
    - name: Create database
      run: docker-compose -f docker-compose.test.yml exec -T -u root appquarium-php-apigateway bin/console d:m:s:c --env=test
    - name: Load fixtures
      run: docker-compose -f docker-compose.test.yml exec -T -u root appquarium-php-apigateway bin/console t:f:l --env=test
    - name: Launch tests
      run: docker-compose -f docker-compose.test.yml exec -T -u root appquarium-php-apigateway bin/phpunit